# Configura»õie pentru rularea ambelor containere Docker.


services:
  monitoring:
    build:
      context: ../        # context: platforma-monitorizare/
      dockerfile: docker/monitoring/Dockerfile
    container_name: monitoring
    volumes:
      - system_data:/data
    networks:
      - monitor-net
    environment:
      INTERVAL: 5

  backup:
    build:
      context: ../
      dockerfile: docker/backup/Dockerfile
    container_name: backup
    volumes:
      - system_data:/data
    networks:
      - monitor-net
    environment:
      BACKUP_INTERVAL: 5
      BACKUP_DIR: /data/backup

volumes:
  system_data:

networks:
  monitor-net:

