apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring-app
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoring-app
  template:
    metadata:
      labels:
        app: monitoring-app
    spec:
      containers:
        - name: monitoring
          image: monitoring:latest
          imagePullPolicy: Never
          env:
            - name: INTERVAL
              value: "5"
          volumeMounts:
            - name: data-volume
              mountPath: /data

        - name: backup
          image: backup:latest
          imagePullPolicy: Never
          env:
            - name: BACKUP_INTERVAL
              value: "5"
            - name: BACKUP_DIR
              value: /data/backup
          volumeMounts:
            - name: data-volume
              mountPath: /data

        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data-volume
              mountPath: /usr/share/nginx/html/logs

      volumes:
        - name: data-volume
          emptyDir: {}

